#:schema node_modules/wrangler/config-schema.json
name = "image-pixelator"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "image-pixelator"

[vars]
# Add your environment variables here
# NEXT_PUBLIC_...

# [kv_namespaces]
# [[kv_namespaces]]
# binding = "NEXT_CACHE_WORKERS_KV"
# id = "<YOUR_KV_NAMESPACE_ID>"
